### ISSUE TITLE
Can't install.

### ISSUE THREAD

**Issue by jorgeepena** [jjcodes78/mikrotikapi#1]
Hello! Using composer require just send a bunch of errors. Is there a way to fix this?

`composer require jjsquady/mikrotikapi
Using version ^0.4.0 for jjsquady/mikrotikapi
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing pear2/net_transmitter (1.0.0a5): Downloading (100%)         
  - Installing pear2/net_routeros (1.0.0b5): Downloading (100%)         
  - Installing jjsquady/mikrotikapi (0.4.0): Downloading (0%)    Failed to download jjsquady/mikrotikapi from dist: The "https://codeload.github.com/jjsquady/mikrotikapi/legacy.zip/ad37a6df73f2f686922a4f4d9ae7674b6f5c5bbf" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing jjsquady/mikrotikapi (0.4.0): Cloning ad37a6df73 from cache
    ad37a6df73f2f686922a4f4d9ae7674b6f5c5bbf is gone (history was rewritten?)

Installation failed, reverting ./composer.json to its original content.

                                                                               
  [RuntimeException]                                                           
  Failed to execute git checkout 'ad37a6df73f2f686922a4f4d9ae7674b6f5c5bbf' -  
  - && git reset --hard 'ad37a6df73f2f686922a4f4d9ae7674b6f5c5bbf' --          
                                                                               
  fatal: reference is not a tree: ad37a6df73f2f686922a4f4d9ae7674b6f5c5bbf `

**Comment by paclw-cory** [comment]
Same problem here trying to install on 5.8.

Anything I can do to help?

**Comment by jjcodes78** [comment]
Hi @Eggotron !
Sorry for that, I ve updated the packagist registry. I think that should work now.

**Comment by jjcodes78** [comment]
composer require jjsquady/mikrotikapi:0.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing pear2/net_transmitter (1.0.0a5): Downloading (100%)         
  - Installing pear2/net_routeros (1.0.0b5): Loading from cache
  - Installing jjsquady/mikrotikapi (0.1): Downloading (100%)       

minimum-stability: dev

I'm working on a simplified version... without pear2/net_routeros complexity. I ll publish a new branch with this version using the RouterOS php class.

**Comment by paclw-cory** [comment]
Still getting this today:

# composer require jjsquady/mikrotikapi

Using version ^0.1.0 for jjsquady/mikrotikapi
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing pear2/net_transmitter (1.0.0a5): Loading from cache
  - Installing pear2/net_routeros (1.0.0b5): Loading from cache
  - Installing jjsquady/mikrotikapi (0.1): Downloading (100%)         
pear2/net_transmitter suggests installing pear2/cache_shm (>=0.1.3)
pear2/net_transmitter suggests installing ext-apc (>=3.0.13)
pear2/net_transmitter suggests installing ext-wincache (>=1.1.0)
pear2/net_routeros suggests installing pear2/cache_shm (Enables persistent connections.)
pear2/net_routeros suggests installing pear2/console_commandline (Enables the console)
pear2/net_routeros suggests installing pear2/console_color (Enables colors in the console)
pear2/net_routeros suggests installing ext-apc (This or Wincache is required for persistent connections.)
pear2/net_routeros suggests installing ext-wincache (This or APC is required for persistent connections. Reccomended instead of APC on Windows.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In ProviderRepository.php line 208:
                                                                         
  Class 'jjsquady\MikrotikApi\MikrotikServiceProvider::class' not found  
                                                                         
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by jjcodes78** [comment]
Hi!

I made a mistake leaving *::class* in "extra" -> "provders" in composer.json :(

**WRONG**
```
"extra": {
    "laravel": {
      "providers": [
        "jjsquady\\MikrotikApi\\MikrotikServiceProvider::class"
      ],
      "aliases": {
        "Mikrotik": "jjsquady\\MikrotikApi\\Facades\\MikrotikFacade::class"
      }
    }
  }
```

**RIGHT**
```
"extra": {
    "laravel": {
      "providers": [
        "jjsquady\\MikrotikApi\\MikrotikServiceProvider"
      ],
      "aliases": {
        "Mikrotik": "jjsquady\\MikrotikApi\\Facades\\MikrotikFacade"
      }
    }
  }
```

To avoid the error remove `::class` in `vendor/composer/installed.json` and `bootstrap/cache/packages.php` files.

After that... the **php artisan package:discover** works.

I'll fix this in a next commit.
